//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerOneMovement"",
            ""id"": ""a4976d82-eaf0-4d69-83fc-907c9418ef07"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""90adccc0-25e3-44c4-b7a0-e7cdbcdd3e33"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""69ac8c43-d20d-45bf-a2e9-f6452a193258"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6175ba59-a1ec-4c8c-b07d-c1334628129b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""37da62ba-b142-4bb1-b4eb-8b6b11a63c5c"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d81dddda-0e36-4edb-b96d-9070eaad1ab6"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""71981dd5-01c1-4cf1-9489-0fd914af3744"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerTwoMovement"",
            ""id"": ""00cb9ac1-0e9c-4b3b-beb8-4ec124b5e0c5"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""843f2f69-b912-44bd-ad7b-ef7a814c68db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""311145a1-aba5-41eb-8155-1b035235b6d0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4eec1ebb-f07d-497c-8e61-9bc1887db9a8"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b911bf8d-6570-4119-9919-fbfe5413d013"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4aed4338-b852-4d2f-b94b-d5a88f010512"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e3ad89ab-bb53-4c33-8d30-13c1e1c95e61"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerOneMovement
        m_PlayerOneMovement = asset.FindActionMap("PlayerOneMovement", throwIfNotFound: true);
        m_PlayerOneMovement_Move = m_PlayerOneMovement.FindAction("Move", throwIfNotFound: true);
        // PlayerTwoMovement
        m_PlayerTwoMovement = asset.FindActionMap("PlayerTwoMovement", throwIfNotFound: true);
        m_PlayerTwoMovement_Move = m_PlayerTwoMovement.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerOneMovement
    private readonly InputActionMap m_PlayerOneMovement;
    private IPlayerOneMovementActions m_PlayerOneMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerOneMovement_Move;
    public struct PlayerOneMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerOneMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerOneMovement_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerOneMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerOneMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerOneMovementActions instance)
        {
            if (m_Wrapper.m_PlayerOneMovementActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_PlayerOneMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public PlayerOneMovementActions @PlayerOneMovement => new PlayerOneMovementActions(this);

    // PlayerTwoMovement
    private readonly InputActionMap m_PlayerTwoMovement;
    private IPlayerTwoMovementActions m_PlayerTwoMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerTwoMovement_Move;
    public struct PlayerTwoMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerTwoMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerTwoMovement_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTwoMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTwoMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerTwoMovementActions instance)
        {
            if (m_Wrapper.m_PlayerTwoMovementActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerTwoMovementActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerTwoMovementActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerTwoMovementActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_PlayerTwoMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public PlayerTwoMovementActions @PlayerTwoMovement => new PlayerTwoMovementActions(this);
    public interface IPlayerOneMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPlayerTwoMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
