//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/Player Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerOneMovement"",
            ""id"": ""a4976d82-eaf0-4d69-83fc-907c9418ef07"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""90adccc0-25e3-44c4-b7a0-e7cdbcdd3e33"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""43c527c8-414f-4de2-b8c8-a5ad57fc0d5a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""a62b2857-cc39-4c47-a117-15529c075f5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""04163954-10c7-4af3-8da6-546d4cc63972"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a12d4694-3cb3-4fda-9d23-4a6647214f69"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""a194d1ff-2822-464a-b480-30cfe9eb196a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""33da50f1-3657-4466-bd6a-4005b865cc36"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""9cf6bf53-f358-4cd6-a5b7-ed744550f2de"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""cf93fec0-22e4-4614-b251-ec65b985b6af"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""55095254-fb4c-41cf-8730-bbff49d14f75"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f04d47b-85d7-40ed-9f7c-a9c99e9e0045"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fad7dfa2-4b3f-4458-b5ae-4e6e12a3aba0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerOneMovement
        m_PlayerOneMovement = asset.FindActionMap("PlayerOneMovement", throwIfNotFound: true);
        m_PlayerOneMovement_Move = m_PlayerOneMovement.FindAction("Move", throwIfNotFound: true);
        m_PlayerOneMovement_Aim = m_PlayerOneMovement.FindAction("Aim", throwIfNotFound: true);
        m_PlayerOneMovement_Shoot = m_PlayerOneMovement.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerOneMovement_Interact = m_PlayerOneMovement.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerOneMovement
    private readonly InputActionMap m_PlayerOneMovement;
    private IPlayerOneMovementActions m_PlayerOneMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerOneMovement_Move;
    private readonly InputAction m_PlayerOneMovement_Aim;
    private readonly InputAction m_PlayerOneMovement_Shoot;
    private readonly InputAction m_PlayerOneMovement_Interact;
    public struct PlayerOneMovementActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerOneMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerOneMovement_Move;
        public InputAction @Aim => m_Wrapper.m_PlayerOneMovement_Aim;
        public InputAction @Shoot => m_Wrapper.m_PlayerOneMovement_Shoot;
        public InputAction @Interact => m_Wrapper.m_PlayerOneMovement_Interact;
        public InputActionMap Get() { return m_Wrapper.m_PlayerOneMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerOneMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerOneMovementActions instance)
        {
            if (m_Wrapper.m_PlayerOneMovementActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnMove;
                @Aim.started -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnAim;
                @Shoot.started -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnShoot;
                @Interact.started -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerOneMovementActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_PlayerOneMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public PlayerOneMovementActions @PlayerOneMovement => new PlayerOneMovementActions(this);
    public interface IPlayerOneMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
